The commit considers the complete tasks until the "Step 5 Arrays."
sergey-goryushko/aqa-course-goryushko pull request #2
Opened 2023-05-09 17:21 UTC by sergey-goryushko

2023-05-10 14:55 UTC, myevlentiev requested changes

2023-05-10 14:55 UTC, myevlentiev commented on src/StepFirst.java
> +        System.out.print(hz);
тут можно поместить все в один System.out.print

2023-05-10 14:55 UTC, myevlentiev commented on src/IncrementDecrement.java
> +        IncrementDecrement.decrement();
нет пре-инкремента и пре-декремента

2023-05-10 14:55 UTC, myevlentiev commented on src/Conditions.java
> +    public void scanInt(){
сделай reformate code
![image](https://github.com/sergey-goryushko/aqa-course-goryushko/assets/92365287/aa29696d-43e5-4a62-85a6-1af796747a74)

2023-05-10 14:55 UTC, myevlentiev commented on src/Conditions.java
> +        if ((floatNumber % 2 == 0 && floatNumber > 10) || (floatNumber == 15)){
скобки вокруг floatNumber == 15 не нужны

2023-05-10 14:55 UTC, myevlentiev commented on src/Loops.java
> +        System.out.println("\n");
к примеру для числа 11 ничего не выводится, по идее должно выводиться 1

2023-05-10 15:48 UTC, sergey-goryushko commented on src/StepFirst.java
> +        System.out.print(hz);
готово, сам не понимаю почему так сделал)

2023-05-10 15:53 UTC, sergey-goryushko commented on src/Conditions.java
> +    public void scanInt(){
готово

2023-05-10 15:56 UTC, sergey-goryushko commented on src/Conditions.java
> +        if ((floatNumber % 2 == 0 && floatNumber > 10) || (floatNumber == 15)){
скобки убрал

2023-05-10 16:21 UTC, sergey-goryushko commented on src/IncrementDecrement.java
> +        IncrementDecrement.decrement();
добавил

2023-05-11 17:21 UTC, sergey-goryushko commented on src/Loops.java
> +        System.out.println("\n");
переписал реализацию

2023-05-12 14:25 UTC, merged