There are the tasks for Massifs and Strings in this commit.
sergey-goryushko/aqa-course-goryushko pull request #3
Opened 2023-05-22 14:55 UTC by sergey-goryushko

2023-05-24 22:45 UTC, myevlentiev requested changes

2023-05-24 22:45 UTC, myevlentiev commented on src/com/course/syntax/Massifs.java
> +        average = sum / 2;
нужно вывести среднее  значение

2023-05-24 22:45 UTC, myevlentiev commented on src/com/course/syntax/Massifs.java
> +            mergedArray[i] = i;
не похоже что тут происходит объединение массивов. У тебя тут создаются два массива, у которых все ячейки содержат нули, ты берешь их размеры, и в цикле заполняешь новый массив, генерируя новые данные, а не используя данные из своих текущих массивов

попробуй объединить, задав к примеру два статических массивы, без генерации что бы не усложнять
int[] array1 = {1, 2, 3, 4};
int[] array2 = {5, 6, 8, 12, 4};

2023-05-24 22:45 UTC, myevlentiev commented on src/com/course/syntax/Strings.java
> +        strings.deleteSpacesAndMakeLineInUppercase();
нужно что бы результат был такой, удалить пробелы, перевести в верхний регистр и вывести в консоль результат по буквам в столбце

one two
O
N
E
T
W
O

2023-05-25 14:13 UTC, sergey-goryushko commented on src/com/course/syntax/Massifs.java
> +        average = sum / 2;
исправлено

2023-05-25 15:10 UTC, sergey-goryushko commented on src/com/course/syntax/Massifs.java
> +            mergedArray[i] = i;
переписал реализацию

2023-05-25 16:29 UTC, merged