Java OOP tasks.
sergey-goryushko/aqa-course-goryushko pull request #4
Opened 2023-06-29 15:37 UTC by sergey-goryushko

2023-07-03 07:16 UTC, myevlentiev requested changes

2023-07-03 07:16 UTC, myevlentiev commented on src/com/course/syntax/Card.java
> +    public void setCardType(String cardType) {
через setCardType можно установить любое значение cartType, следует добавить проверку как в конструкторе на проверку Visa и Master Card

2023-07-03 07:16 UTC, myevlentiev commented on src/com/course/syntax/Manager.java
> +    public static void main(String[] args) {
в классе Manager не должно быть сторонних методов, вынеси метод main в какой-то отдельный тестовый класс

2023-07-03 07:16 UTC, myevlentiev commented on src/com/course/syntax/Manager.java
> +    private String position = "manager";
у данного поля не должно быть заданного значения

2023-07-04 16:44 UTC, sergey-goryushko commented on src/com/course/syntax/Manager.java
> +    private String position = "manager";
значение удалил

2023-07-04 16:46 UTC, sergey-goryushko commented on src/com/course/syntax/Manager.java
> +    public static void main(String[] args) {
сделал

2023-07-04 16:49 UTC, sergey-goryushko commented on src/com/course/syntax/User.java
> +    public User() {
лишний конструктор удалил

2023-07-04 16:51 UTC, sergey-goryushko commented on src/com/course/syntax/User.java
> +    private int id;
сделал

2023-07-04 16:54 UTC, sergey-goryushko commented on src/com/course/syntax/User.java
> +    public static void main(String[] args) {
сделал

2023-07-04 16:57 UTC, sergey-goryushko commented on src/com/course/syntax/User.java
> +    private String email = "a@c.gmail.com";
удалил значения полей

2023-07-04 16:58 UTC, sergey-goryushko commented on src/com/course/syntax/User.java
> +    private String deliveryAddress;
отрефакторил)

2023-07-04 17:04 UTC, sergey-goryushko commented on src/com/course/syntax/User.java
> +    private String role;
отрефакторил)

2023-07-04 17:11 UTC, sergey-goryushko commented on src/com/course/syntax/User.java
> +    private String manager;
сделал

2023-07-06 15:06 UTC, sergey-goryushko commented on src/com/course/syntax/Card.java
> +    public void setCardType(String cardType) {
валидацию добавил

2023-07-07 10:34 UTC, sergey-goryushko commented on src/com/course/syntax/User.java
> +        Roles roles = new Roles(true, false, true, false);//it's customer type
переделал

2023-07-10 09:40 UTC, myevlentiev commented on src/com/course/syntax/User.java
> +    private Roles role = new Roles("main customer");
роль должна задаваться при создании пользователя, по умолчания дефолтной роли не должно быть

2023-07-10 09:40 UTC, myevlentiev commented on src/com/course/syntax/Card.java
> +    public void setCardType(String cardType) {
в методе setCardType проверки не добавил )

2023-07-10 11:07 UTC, sergey-goryushko commented on src/com/course/syntax/Card.java
> +    public void setCardType(String cardType) {
Axaxa) да, реализацию в конструкторе переписал, а копипаст не сделал)

2023-07-12 16:24 UTC, merged